### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by sabr5840** [sabr5840/Visualization#25]
**Fordele ved Separate Workflows**
Modularitet: Backend og frontend har forskellige byggemetoder og værktøjer, så det giver mening at have separate workflows.
Automatisering: Ændringer i enten backend eller frontend kan bygges og deployes uden manuel indsats.
Feedback-loop: Du får hurtigt besked om eventuelle fejl i backend eller frontend.

## GitHub Actions til Backend

Dette workflow automatiserer deployment af din backend til Azure.

**Opsætning**
1. Opret en fil: .github/workflows/backend.yml.
2. Workflow:

```
name: Deploy Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: npm test

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-azure-app-name>
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

```

3. Tilføj din Azure Web App-publikationsprofil som en hemmelighed i GitHub (AZURE_WEBAPP_PUBLISH_PROFILE).
4. Push din backend-kode til main, og deployment vil ske automatisk.

## GitHub Actions til Frontend

*For din React Native-frontend kan workflowet hjælpe dig med at bygge og distribuere appen. Da du bruger Expo, er EAS Build (Expo Application Services) perfekt til at bygge produktionsklare .apk og .ipa filer

**Opsætning:**

1. Opret en fil: .github/workflows/frontend.yml.
2. Workflow:

```
name: Build React Native App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Login to Expo
        run: npx expo login --username ${{ secrets.EXPO_USERNAME }} --password ${{ secrets.EXPO_PASSWORD }}

      - name: Build App
        run: npx eas build --platform all
```

3. Secrets
- Tilføj dine Expo-loginoplysninger som hemmeligheder i GitHub:
    - EXPO_USERNAME
    - EXPO_PASSWORD
4. Output:
    -  Dette workflow genererer en produktionsklar app. Bygningerne kan hentes fra Expo.
